import type { User, UserRole, Permission } from './redux/authSlice';
import type { PunchEntry, SaleEntry } from './types';

// Dummy Users for Testing
export const dummyUsers: User[] = [
  {
    id: 'user-1',
    name: 'Admin User',
    email: 'admin@chemos.com',
    role: 'admin',
    token: 'token-admin-123',
    permissions: {
      canViewPurchases: true,
      canViewSales: true,
      canEditPurchases: true,
      canEditSales: true,
    },
  },
  {
    id: 'user-2',
    name: 'Purchase Manager',
    email: 'purchase@chemos.com',
    role: 'purchase',
    token: 'token-purchase-456',
    permissions: {
      canViewPurchases: true,
      canViewSales: false,
      canEditPurchases: true,
      canEditSales: false,
    },
  },
  {
    id: 'user-3',
    name: 'Sales Manager',
    email: 'sales@chemos.com',
    role: 'sales',
    token: 'token-sales-789',
    permissions: {
      canViewPurchases: false,
      canViewSales: true,
      canEditPurchases: false,
      canEditSales: true,
    },
  },
  {
    id: 'user-4',
    name: 'Both Access User',
    email: 'both@chemos.com',
    role: 'both',
    token: 'token-both-101',
    permissions: {
      canViewPurchases: true,
      canViewSales: true,
      canEditPurchases: true,
      canEditSales: true,
    },
  },
];

// Dummy Purchase Orders (PunchEntry)
export const dummyPurchaseOrders: PunchEntry[] = [
  {
    id: 1,
    ts: new Date('2026-06-09T10:30:00').toISOString(),
    company_to: 'Chemos India Pvt Ltd',
    company_from: 'Global Chemicals Ltd',
    product: 'Sodium Bicarbonate',
    vessel_name: 'MV Ocean Glory',
    shipment: 'Container',
    quantity: 100,
    price_fc: 850,
    currency: 'USD',
    offer_usd: 850,
    exchange_rate: 83.5,
    price_inr: 70975,
    delivery_term: 'CIF',
    payment_days: '45 Days',
    port: 'Nhava Sheva',
    market_price: 72000,
    market_status: 'Ready Market',
    cost_price: 70975,
    replacement_cost: 71500,
    expense: 2500,
    custom_duty: 7500,
    sws: 1200,
    add: 800,
    other_expense: 500,
    make: 'Solvay',
    packaging: '25 KG Bags',
    origin: 'Turkey',
    sales_person: 'Rajesh Kumar',
    broker_name: 'Trade Connect',
  },
  {
    id: 2,
    ts: new Date('2026-06-08T14:15:00').toISOString(),
    company_to: 'Chemos India Pvt Ltd',
    company_from: 'Asian Suppliers Co',
    product: 'Citric Acid Anhydrous',
    vessel_name: 'MV Pacific Star',
    shipment: 'Bulk',
    quantity: 200,
    price_fc: 1200,
    currency: 'USD',
    offer_usd: 1200,
    exchange_rate: 83.5,
    price_inr: 100200,
    delivery_term: 'FOB',
    payment_days: '30 Days',
    port: 'Mumbai',
    market_price: 102000,
    market_status: 'Spot',
    cost_price: 100200,
    replacement_cost: 101000,
    expense: 3000,
    custom_duty: 10000,
    sws: 1500,
    add: 1000,
    other_expense: 500,
    make: 'Weifang',
    packaging: '50 KG Bags',
    origin: 'China',
    sales_person: 'Priya Sharma',
    broker_name: 'Global Trade Partners',
  },
  {
    id: 3,
    ts: new Date('2026-06-07T09:45:00').toISOString(),
    company_to: 'Chemos India Pvt Ltd',
    company_from: 'Euro Chem Industries',
    product: 'Potassium Carbonate',
    vessel_name: 'MV Baltic Breeze',
    shipment: 'Container',
    quantity: 150,
    price_fc: 950,
    currency: 'EUR',
    offer_usd: 1045,
    exchange_rate: 90.2,
    price_inr: 94259,
    delivery_term: 'CIF',
    payment_days: '60 Days',
    port: 'Chennai',
    market_price: 96000,
    market_status: 'Incoming',
    cost_price: 94259,
    replacement_cost: 95000,
    expense: 2800,
    custom_duty: 8500,
    sws: 1300,
    add: 900,
    other_expense: 600,
    make: 'BASF',
    packaging: '25 KG Bags',
    origin: 'Germany',
    sales_person: 'Amit Patel',
  },
  {
    id: 4,
    ts: new Date('2026-06-06T16:20:00').toISOString(),
    company_to: 'Chemos India Pvt Ltd',
    company_from: 'Middle East Traders',
    product: 'Phosphoric Acid 85%',
    vessel_name: 'MV Desert Carrier',
    shipment: 'Tanker',
    quantity: 300,
    price_fc: 780,
    currency: 'USD',
    offer_usd: 780,
    exchange_rate: 83.5,
    price_inr: 65130,
    delivery_term: 'CFR',
    payment_days: '45 Days',
    port: 'Kandla',
    market_price: 66000,
    market_status: 'Ready Market',
    cost_price: 65130,
    replacement_cost: 65500,
    expense: 4000,
    custom_duty: 6500,
    sws: 2000,
    add: 1200,
    other_expense: 800,
    make: 'OCP',
    packaging: 'Bulk Liquid',
    origin: 'Morocco',
    sales_person: 'Neha Singh',
    broker_name: 'Maritime Brokers Inc',
  },
  {
    id: 5,
    ts: new Date('2026-06-05T11:00:00').toISOString(),
    company_to: 'Chemos India Pvt Ltd',
    company_from: 'Southeast Asia Chemicals',
    product: 'Acetic Acid Glacial',
    vessel_name: 'MV Monsoon Express',
    shipment: 'ISO Tank',
    quantity: 120,
    price_fc: 920,
    currency: 'USD',
    offer_usd: 920,
    exchange_rate: 83.5,
    price_inr: 76820,
    delivery_term: 'CIF',
    payment_days: '30 Days',
    port: 'Vizag',
    market_price: 78000,
    market_status: 'Spot',
    cost_price: 76820,
    replacement_cost: 77500,
    expense: 2200,
    custom_duty: 7700,
    sws: 1100,
    add: 750,
    other_expense: 450,
    make: 'Celanese',
    packaging: 'ISO Tank',
    origin: 'Malaysia',
    sales_person: 'Vikram Reddy',
  },
];

// Dummy Sale Orders (SaleEntry)
export const dummySaleOrders: SaleEntry[] = [
  {
    id: 101,
    ts: new Date('2026-06-09T11:00:00').toISOString(),
    sale_type: 'GST Sale',
    company_to: 'Pharma Industries Ltd',
    company_from: 'Chemos India Pvt Ltd',
    product: 'Sodium Bicarbonate',
    quantity: 50,
    price: 75,
    payment: 'Net 30',
    delivery_term: 'Ex-Works',
    port: 'Mumbai',
    market_price: 72000,
    market_status: 'Ready Market',
    storage_days: 15,
    transit_tolerance: '±2%',
    make: 'Solvay',
    packaging: '25 KG Bags',
    origin: 'Turkey',
    message: 'Urgent delivery required',
    sales_person: 'Rajesh Kumar',
    broker_name: 'Direct Sale',
  },
  {
    id: 102,
    ts: new Date('2026-06-08T15:30:00').toISOString(),
    sale_type: 'GST Sale',
    company_to: 'Food Processing Co',
    company_from: 'Chemos India Pvt Ltd',
    product: 'Citric Acid Anhydrous',
    quantity: 100,
    price: 108,
    payment: 'Net 45',
    delivery_term: 'FOR',
    port: 'Delhi',
    market_price: 102000,
    market_status: 'Spot',
    storage_days: 20,
    transit_tolerance: '±1.5%',
    make: 'Weifang',
    packaging: '50 KG Bags',
    origin: 'China',
    message: 'Quality certificate required',
    sales_person: 'Priya Sharma',
  },
  {
    id: 103,
    ts: new Date('2026-06-07T10:15:00').toISOString(),
    sale_type: 'Bond Sale',
    company_to: 'Export House India',
    company_from: 'Chemos India Pvt Ltd',
    product: 'Potassium Carbonate',
    quantity: 80,
    price: 98,
    payment: 'LC at Sight',
    delivery_term: 'FOB',
    port: 'Chennai',
    market_price: 96000,
    market_status: 'Incoming',
    storage_days: 10,
    transit_tolerance: '±2%',
    make: 'BASF',
    packaging: '25 KG Bags',
    origin: 'Germany',
    message: 'Export documentation in progress',
    sales_person: 'Amit Patel',
    broker_name: 'Export Facilitators',
  },
  {
    id: 104,
    ts: new Date('2026-06-06T17:00:00').toISOString(),
    sale_type: 'GST Sale',
    company_to: 'Fertilizer Corporation',
    company_from: 'Chemos India Pvt Ltd',
    product: 'Phosphoric Acid 85%',
    quantity: 150,
    price: 68,
    payment: 'Net 60',
    delivery_term: 'CFR',
    port: 'Kandla',
    market_price: 66000,
    market_status: 'Ready Market',
    storage_days: 25,
    transit_tolerance: '±3%',
    make: 'OCP',
    packaging: 'Bulk Liquid',
    origin: 'Morocco',
    message: 'Regular customer - priority delivery',
    sales_person: 'Neha Singh',
  },
  {
    id: 105,
    ts: new Date('2026-06-05T12:30:00').toISOString(),
    sale_type: 'GST Sale',
    company_to: 'Textile Mills Ltd',
    company_from: 'Chemos India Pvt Ltd',
    product: 'Acetic Acid Glacial',
    quantity: 60,
    price: 82,
    payment: 'Net 30',
    delivery_term: 'Ex-Works',
    port: 'Surat',
    market_price: 78000,
    market_status: 'Spot',
    storage_days: 12,
    transit_tolerance: '±1%',
    make: 'Celanese',
    packaging: 'ISO Tank',
    origin: 'Malaysia',
    message: 'Sample approved by buyer',
    sales_person: 'Vikram Reddy',
    broker_name: 'Industrial Brokers',
  },
  {
    id: 106,
    ts: new Date('2026-06-04T09:20:00').toISOString(),
    sale_type: 'Bond Sale',
    company_to: 'International Traders LLC',
    company_from: 'Chemos India Pvt Ltd',
    product: 'Sodium Bicarbonate',
    quantity: 75,
    price: 77,
    payment: 'LC 90 Days',
    delivery_term: 'CIF',
    port: 'Nhava Sheva',
    market_price: 72000,
    market_status: 'Ready Market',
    storage_days: 18,
    transit_tolerance: '±2%',
    make: 'Solvay',
    packaging: '25 KG Bags',
    origin: 'Turkey',
    message: 'Re-export to Middle East',
    sales_person: 'Rajesh Kumar',
  },
];

// Helper function to get user by token
export function getUserByToken(token: string): User | undefined {
  return dummyUsers.find((user) => user.token === token);
}

// Helper function to get user by email
export function getUserByEmail(email: string): User | undefined {
  return dummyUsers.find((user) => user.email === email);
}

// Helper function to simulate login
export function simulateLogin(email: string): User | null {
  const user = getUserByEmail(email);
  return user || null;
}
